name: Manual run (matrix)
on:
  workflow_dispatch:

jobs:
  scripterio-example-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22, 23, 24]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npx playwright install chromium --with-deps

      - name: Install dependencies
        run: npm install

      - name: run test
        run: npm run test
