name: Manual run
on:
  workflow_dispatch:
    
jobs:
  real-test-js-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npm i playwright-chromium

      - name: Install dependencies
        run: npm install
        
      - name: run test
        run: npm run test