name: Manual run
on:
  workflow_dispatch:

jobs:
  scripterio-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npx playwright install chromium --with-deps

      - name: Install dependencies
        run: npm install
        
      - name: run test
        run: npm run test